spring:
  redis:
    jedis:
      pool:
        min-idle: 100
        max-active: 300
        max-idle: 500
logging:
  level:
    org: info
    com.dataType: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] %logger{50}  : %msg%n"
