
server:
  port: 8081
  servlet:
    context-path: /kill
# log
logging:
  level:
    com.secondkill.mapper: DEBUG
    com.secondkill.service: DEBUG
    com.fasterxml.jackson: INFO
    org:
      springframework: INFO
      mybatis: INFO
      redisson: INFO
      hibernate: INFO
    io:
      netty: INFO
spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT-8"
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/db_second_kill?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: "123456"
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxPoolPreparedStatementPerConnectionSize: 20
      poolPreparedStatements: false
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.qq.com
    username: 2482600250@qq.com
    password: www19951208
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# mybatis
mybatis:
  config-location: "classpath:mybatis-config.xml"
  check-config-location: true
  mapper-locations: "classpath:mappers/*.xml"
  type-aliases-package: "com.secondkill.entity"






