server:
  port: 8080
  servlet:
    context-path: /distribute
logging:
  level:
    com.fasterxml.jackson: INFO
    org:
      springframework: INFO
      mybatis: INFO
      redisson: INFO
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/db_distribute_lock?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: "123456"
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxPoolPreparedStatementPerConnectionSize: 20
      poolPreparedStatements: false
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  config-location: "classpath:mybatis-config.xml"
  check-config-location: true
  mapper-locations: "classpath:mappers/*.xml"
  type-aliases-package: "com.example.lock"